/**
 * The LGAs an area can be filed into, and the state each one is in.
 *
 * GENERATED by clearrent/scripts/gen_areas.js from scripts/lagos_areas.json.
 * Do not edit. The app drops a published area whose LGA it does not know, so
 * this list has to match the app's, and a hand-kept copy did not.
 */

export type LgaOption = { value: string; label: string; state: string }

export const LGA_OPTIONS: LgaOption[] = [
  { value: "ikeja", label: "Ikeja LGA", state: "Lagos" },
  { value: "eti_osa", label: "Eti-Osa LGA", state: "Lagos" },
  { value: "lagos_island", label: "Lagos Island LGA", state: "Lagos" },
  { value: "surulere", label: "Surulere LGA", state: "Lagos" },
  { value: "yaba_mainland", label: "Lagos Mainland LGA (Yaba)", state: "Lagos" },
  { value: "kosofe", label: "Kosofe LGA", state: "Lagos" },
  { value: "oshodi_isolo", label: "Oshodi-Isolo LGA", state: "Lagos" },
  { value: "alimosho", label: "Alimosho LGA", state: "Lagos" },
  { value: "ojodu_lcda", label: "Ojodu LGA", state: "Lagos" },
  { value: "shomolu", label: "Shomolu LGA", state: "Lagos" },
  { value: "agege", label: "Agege LGA", state: "Lagos" },
  { value: "ifako_ijaiye", label: "Ifako-Ijaiye LGA", state: "Lagos" },
  { value: "mushin", label: "Mushin LGA", state: "Lagos" },
  { value: "amuwo_odofin", label: "Amuwo-Odofin LGA", state: "Lagos" },
  { value: "apapa", label: "Apapa LGA", state: "Lagos" },
  { value: "ajeromi_ifelodun", label: "Ajeromi-Ifelodun LGA", state: "Lagos" },
  { value: "ojo", label: "Ojo LGA", state: "Lagos" },
  { value: "ikorodu", label: "Ikorodu LGA", state: "Lagos" },
  { value: "badagry", label: "Badagry LGA", state: "Lagos" },
  { value: "epe", label: "Epe LGA", state: "Lagos" },
  { value: "ibeju_lekki", label: "Ibeju-Lekki LGA", state: "Lagos" },
  { value: "obafemi_owode", label: "Lagos outskirts: Obafemi-Owode (Ogun)", state: "Ogun" },
  { value: "other", label: "Other areas (outside our states)", state: "" },
]
